In [1]:
import numpy as np
import matplotlib.pyplot as plt
from astropy.table import Table, Column
#import scipy
import collections
%matplotlib inline


# Crossmatching

In [4]:
#-----------Read matched indices and distances tables--------------#

idx=Table.read('manxmatch_hlc_nsc_idx.txt', format='ascii.no_header')
dist=Table.read('manxmatch_hlc_nsc_d2d.txt', format='ascii.no_header')

#print(len(idx), len(dist))
#dist['col1']

#----------Make list of duplicates--------------------#

#Count duplicates
count=collections.Counter(idx['col1'])
#Turn list into array
count=np.array(count.items())
#Make mask of multiple matches
multimatch=count[:,1]>1

#-------------Match Multiples in Indices array----------------#

#Here, I'm going to create a massive list of the indices of matches I want to throw away.

match=[]
b=[]

for indice in count[multimatch][:,0]:
    #Create mask to find multiple indicies
    a=np.where(idx['col1']==indice)[0]
    #Append matches to list
    match.append([a,idx['col1'][a],dist['col1'][a]])
    #Create mask to find the minimum distance within the matches
    b.append(dist['col1'][a]==min(d for d in dist['col1'][a]))


#Apply the mask to this weird "match" list and make a new list of the right indice matches
nmatch=[]

for i in range(len(match)):
   nmatch.append(match[i][0][b[i]])

#Make nmatch an array
onematch=np.array(nmatch)


#---------------------Final list of matches---------------------#
idx=idx[onematch]

In [227]:
b

[array([ True, False], dtype=bool),
 array([False,  True], dtype=bool),
 array([False,  True], dtype=bool),
 array([ True, False], dtype=bool),
 array([ True, False], dtype=bool),
 array([False, False, False,  True, False], dtype=bool),
 array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True], dtype=bool),
 array([False,  True, False, False], dtype=bool),
 array([ True, False, False], dtype=bool),
 array([ True, False], dtype=bool),
 array([False, False, False,  True], dtype=bool),
 array([ True, False, False, False, False], dtype=bool),
 array([False, False, False, ..., False, False,  True], dtype=bool),
 array([False, False, False, False, False,  True], dtype=bool),
 array([ True, False], dtype=bool),
 array([False, False,  True], dtype=bool),
 array([ True, False], dtype=bool),
 array([ True, False], dtype=bool),
 array([False,  True], dtype=bool),
 array([False,  True],

In [ ]:
#Dino

hlcobj, nscobj = [], []
for matchobj in match:
    hlcobj.append()
    nsc.obj.append(matchobj[1][b[0]])
    
#Make array of object and closest distance
#Make new idx list where you manually input the object and distance using "is in"

# $\chi^2$ Calculation

In [156]:
def chisq(filename1,filename2):
    